version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'surf_forecaster_secret_key'
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_HOST: postgres-app
    POSTGRES_PORT: 5432
    POSTGRES_DB: ${POSTGRES_DB}
    DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
    APP_BASE_URL: ${APP_BASE_URL}
    PYTHONPATH: /opt/airflow/src
    AIRFLOW__WEBSERVER__WORKERS: 1
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./config:/opt/airflow/config
    - ./dbt_surf_forecaster:/opt/airflow/dbt
  depends_on:
    postgres-airflow:
      condition: service_healthy
    postgres-app:
      condition: service_healthy

services:
  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  postgres-app:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/label_sessions.sql:/docker-entrypoint-initdb.d/label_sessions.sql
      - postgres-app-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    user: "0:0"
    command: bash -c "chmod -R 777 /opt/airflow/dbt && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8081:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    restart: always

  labeling_app:
    build:
      context: .
      dockerfile: rating_app.Dockerfile
    container_name: labeling_app
    restart: always
    environment:
      POSTGRES_HOST: postgres-app
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}    
    ports:
      - "8000:8000"

volumes:
  postgres-app-data: